const HotelActions = {
  
  FETCH_FAVORITE_HOTELS: "FETCH_FAVORITE_HOTELS",
  FETCH_FAVORITE_HOTELS_SUCCESS: "FETCH_FAVORITE_HOTELS_SUCCESS",
  REMOVE_FAVORITE_HOTEL_REQUEST: "REMOVE_FAVORITE_HOTEL_REQUEST",
  REMOVE_FAVORITE_HOTEL_SUCCESS:"REMOVE_FAVORITE_HOTEL_SUCCESS",
  FETCH_DETAIL_HOTEL:"FETCH_DETAIL_HOTEL",
  FETCH_DETAIL_HOTEL_SUCCESS:"FETCH_DETAIL_HOTEL_SUCCESS",
};
export default HotelActions;
