const HotelActions = {
  
  FETCH_OWNER_HOTEL:"FETCH_OWNER_HOTEL",
  FETCH_OWNER_HOTEL_SUCCESS:"FETCH_OWNER_HOTEL_SUCCESS",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  UPDATE_HOTEL_SUCCESS: "UPDATE_HOTEL_SUCCESS",
  UPDATE_HOTEL_SERVICE_STATUS: "UPDATE_HOTEL_SERVICE_STATUS",
  UPDATE_HOTEL_SERVICE_STATUS_SUCCESS: "UPDATE_HOTEL_SERVICE_STATUS_SUCCESS",  
  CREATE_HOTEL_SERVICE: "CREATE_HOTEL_SERVICE",
  CREATE_HOTEL_SERVICE_SUCCESS: "CREATE_HOTEL_SERVICE_SUCCESS",

};
export default HotelActions;
