const HotelActions = {
  FETCH_FAVORITE_HOTELS: "FETCH_FAVORITE_HOTELS",
  FETCH_FAVORITE_HOTELS_SUCCESS: "FETCH_FAVORITE_HOTELS_SUCCESS",

  FETCH_ALL_HOTEL: "FETCH_ALL_HOTEL",
  FETCH_All_HOTEL_SUCCESS: " FETCH_All_HOTEL_SUCCESS",

  FETCH_TOP3_HOTEL: "FETCH_TOP3_HOTEL",
  FETCH_TOP3_HOTEL_SUCCESS: "FETCH_TOP3_HOTEL_SUCCESS",
  
  FETCH_OWNER_HOTEL:"FETCH_OWNER_HOTEL",
  FETCH_OWNER_HOTEL_SUCCESS:"FETCH_OWNER_HOTEL_SUCCESS",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  UPDATE_HOTEL_SUCCESS: "UPDATE_HOTEL_SUCCESS",
};
export default HotelActions;
