const HotelActions = {
  
  FETCH_OWNER_HOTEL:"FETCH_OWNER_HOTEL",
  FETCH_OWNER_HOTEL_SUCCESS:"FETCH_OWNER_HOTEL_SUCCESS",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  UPDATE_HOTEL_SUCCESS: "UPDATE_HOTEL_SUCCESS",
};
export default HotelActions;
